@function_app_HostAddress = http://localhost:7005

### Prompt the agent
POST {{function_app_HostAddress}}/api/SequentialAgent_HttpStart HTTP/1.1
Content-Type: text/plain

Bukayo Saka’s goal just before half-time saw us reach the Champions League final for the second time in our history as we beat Atletico Madrid 1-0 at an ecstatic Emirates Stadium.
With the game finely poised after last week’s 1-1 draw in the Spanish capital, we grabbed the all-important goal on 44 minutes when Leandro Trossard’s shot was parried into Saka’s path to tuck home, and set up a grandstand second 45.
Some excellent defensive shifts saw us repel everything the visitors threw at us, and backed by deafening support throughout, we got over the line to book our spot in the final in Budapest at the end of the month against either Bayern Munich or Paris Saint-Germain, and one last step away from our dream of lifting the European Cup for the first time in our history.